-- New concepts, optional for now:
--  Binary equality relation
--  Iff extensionality:
--    rule: (P ↔ Q) ↔ ((P ⇒ Q) ∧ (Q ⇒ P)) ↔
--          (P ↔ Q) = ((P ⇒ Q) ∧ (Q ⇒ P))
--    importance:
--      *equality* as a binary relation
--      accepts validity of interchangeability of ↔ and =
--      which can be useful in certain formal reasoning scenarios
